import Navbar from "@/components/molecules/navbar";
import AuthProvider from "@/providers/auth-provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <AuthProvider>
          <Navbar />
          <main className="px-9 w-full">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
